version: '3.4'

services:
  catalogdb:
    build:
      context: F:/Backend ASP.Net/EShop Microservices/e-shop microsevices/Services/Catalog/CatalogAPI
      dockerfile: Dockerfile
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/