global using buildingblocks.CQRS;
global using FluentValidation;
global using Ordering.Application.Dtos;
global using Ordering.Application.Data;
global using Ordering.Domain.Models;
global using Ordering.Domain.ValueObjects;
global using Ordering.Domain.Enums;
global using Microsoft.EntityFrameworkCore;
global using Ordering.Application.Exceptions;
